# Prize Moeny Data

In [18]:
import pandas as pd
from bs4 import BeautifulSoup
import bs4
import requests

In [19]:
temp_dict = {}
df = pd.DataFrame()

url = 'https://en.wikipedia.org/wiki/List_of_tennis_tournaments'

r  = requests.get(url)
soup = BeautifulSoup(r.text, 'html5lib') 
i = 0

for table in soup.find_all('table', attrs={'style':True}):
    for tr in table.find_all('tr'):
        if i == 0:
            temp_dict[0] = 'Male'
        else:
            temp_dict[0] = 'Female'
        j = 1
        for td in tr.find_all('td'):
            if j == 3 or j == 4 or j == 9:
                temp_dict[j] = td.get_text()
            j += 1
        df = df.append(temp_dict, ignore_index=True)
    i += 1

cols = ['Sex','Type','Tournament','Prize_Money']
df.columns = cols

df.head()

    Sex  Type             Tournament Prize_Money
0  Male   NaN                    NaN         NaN
1  Male   WTF  ATP World Tour Finals  $4,450,000
2  Male  1000   Indian Wells Masters  $4,500,000
3  Male  1000             Miami Open  $3,645,000
4  Male  1000    Monte-Carlo Masters  €2,227,500

In [20]:
df

,Sex,Type,Tournament,Prize_Money
0,Male,NaN,NaN,NaN
1,Male,WTF,ATP World Tour Finals,"$4,450,000"
2,Male,1000,Indian Wells Masters,"$4,500,000"
3,Male,1000,Miami Open,"$3,645,000"
4,Male,1000,Monte-Carlo Masters,"€2,227,500"
5,Male,1000,Madrid Open,"€2,835,000"
6,Male,1000,Italian Open,"€2,227,500"
7,Male,1000,Canadian Open,"$2,430,000"
8,Male,1000,Cincinnati Masters,"$2,430,000"
9,Male,1000,Shanghai Masters,"$3,240,000"
10,Male,1000,Paris Masters,"€2,227,500"
11,Male,500,Rotterdam Open,"€1,150,000"
12,Male,500,Rio Open,"$1,309,770"
13,Male,500,Mexican Open,"$955,000"
14,Male,500,Dubai Tennis Championships,"$1,619,500"
15,Male,500,Barcelona Open,"€1,550,000"
16,Male,500,Halle Open,"€663,750"
17,Male,500,Queen's Club Championships,"£640,000"
18,Male,500,German Open,"€1,000,000"
19,Male,500,Washington Open[2],"$1,165,500"
20,Male,500,Japan Open,"$1,100,000"
21,Male,500,China Open,"$2,100,000"
22,Male,500,Swiss Indoors,"€1,225,000"
23,Male,500,Valencia Open,"€1,357,000"
24,Male,250,Brisbane International,"$372,500"
25,Male,250,Aircel Chennai Open,"$398,250"
26,Male,250,Qatar ExxonMobil Open,"$1,024,000"
27,Male,250,Heineken Open,"$355,500"
28,Male,250,Apia International Sydney,"$372,500"
29,Male,250,Open Sud de France,"€426,605"
...,...,...,...,...
85,Female,International,Brisbane International,"$220,000"
86,Female,International,ASB Classic,"$220,000"
87,Female,International,Moorilla Hobart International,"$220,000"
88,Female,International,PTT Pattaya Open,"$220,000"
89,Female,International,Memphis International,"$220,000"
90,Female,International,XIX COPA BBVA COLSANITAS,"$220,000"
91,Female,International,Abierto Mexicano TELCEL presentado por HSBC,"$220,000"
92,Female,International,Malaysian Open 2011,"$220,000"
93,Female,International,Monterrey Open,"$220,000"
94,Female,International,Andalucia Tennis Experience,"$220,000"
95,Female,International,Grand Prix De SAR La Princesse Lalla Meryem,"$220,000"
96,Female,International,Barcelona Ladies Open,"$220,000"
97,Female,International,Estoril Open,"$220,000"
98,Female,International,Internationaux de Strasbourg,"$220,000"
99,Female,International,e-Boks Sony Ericsson Open,"$220,000"
100,Female,International,Aegon Classic,"$220,000"
101,Female,International,UNICEF Open,"$220,000"
102,Female,International,Collector Swedish Open Women,"$220,000"
103,Female,International,Bucharest Open,"$250,000"
104,Female,International,Internazionali Femminili di Palermo,"$220,000"
105,Female,International,NURNBERGER Gastien Ladies,"$220,000"
106,Female,International,Banka Koper Slovenia Open,"$220,000"
107,Female,International,Mid-Atlantic Women's Tennis Championships,"$220,000"
108,Female,International,Bell Challenge,"$220,000"
109,Female,International,Tashkent Open,"$220,000"
110,Female,International,Guangzhou International Women's Open,"$220,000"
111,Female,International,Hansol Korea Open,"$220,000"
112,Female,International,Generali Ladies Linz,"$220,000"
113,Female,International,HP Japan Women's Open Tennis 2011,"$220,000"
114,Female,International,BGL BNP PARIBAS Luxembourg Open,"$220,000"

In [21]:
df = df.dropna()
df.Prize_Money = df.Prize_Money.str.rstrip().str[1:]
df

,Sex,Type,Tournament,Prize_Money
1,Male,WTF,ATP World Tour Finals,"4,450,000"
2,Male,1000,Indian Wells Masters,"4,500,000"
3,Male,1000,Miami Open,"3,645,000"
4,Male,1000,Monte-Carlo Masters,"2,227,500"
5,Male,1000,Madrid Open,"2,835,000"
6,Male,1000,Italian Open,"2,227,500"
7,Male,1000,Canadian Open,"2,430,000"
8,Male,1000,Cincinnati Masters,"2,430,000"
9,Male,1000,Shanghai Masters,"3,240,000"
10,Male,1000,Paris Masters,"2,227,500"
11,Male,500,Rotterdam Open,"1,150,000"
12,Male,500,Rio Open,"1,309,770"
13,Male,500,Mexican Open,"955,000"
14,Male,500,Dubai Tennis Championships,"1,619,500"
15,Male,500,Barcelona Open,"1,550,000"
16,Male,500,Halle Open,"663,750"
17,Male,500,Queen's Club Championships,"640,000"
18,Male,500,German Open,"1,000,000"
19,Male,500,Washington Open[2],"1,165,500"
20,Male,500,Japan Open,"1,100,000"
21,Male,500,China Open,"2,100,000"
22,Male,500,Swiss Indoors,"1,225,000"
23,Male,500,Valencia Open,"1,357,000"
24,Male,250,Brisbane International,"372,500"
25,Male,250,Aircel Chennai Open,"398,250"
26,Male,250,Qatar ExxonMobil Open,"1,024,000"
27,Male,250,Heineken Open,"355,500"
28,Male,250,Apia International Sydney,"372,500"
29,Male,250,Open Sud de France,"426,605"
30,Male,250,Chile Open,"398,250"
...,...,...,...,...
85,Female,International,Brisbane International,"220,000"
86,Female,International,ASB Classic,"220,000"
87,Female,International,Moorilla Hobart International,"220,000"
88,Female,International,PTT Pattaya Open,"220,000"
89,Female,International,Memphis International,"220,000"
90,Female,International,XIX COPA BBVA COLSANITAS,"220,000"
91,Female,International,Abierto Mexicano TELCEL presentado por HSBC,"220,000"
92,Female,International,Malaysian Open 2011,"220,000"
93,Female,International,Monterrey Open,"220,000"
94,Female,International,Andalucia Tennis Experience,"220,000"
95,Female,International,Grand Prix De SAR La Princesse Lalla Meryem,"220,000"
96,Female,International,Barcelona Ladies Open,"220,000"
97,Female,International,Estoril Open,"220,000"
98,Female,International,Internationaux de Strasbourg,"220,000"
99,Female,International,e-Boks Sony Ericsson Open,"220,000"
100,Female,International,Aegon Classic,"220,000"
101,Female,International,UNICEF Open,"220,000"
102,Female,International,Collector Swedish Open Women,"220,000"
103,Female,International,Bucharest Open,"250,000"
104,Female,International,Internazionali Femminili di Palermo,"220,000"
105,Female,International,NURNBERGER Gastien Ladies,"220,000"
106,Female,International,Banka Koper Slovenia Open,"220,000"
107,Female,International,Mid-Atlantic Women's Tennis Championships,"220,000"
108,Female,International,Bell Challenge,"220,000"
109,Female,International,Tashkent Open,"220,000"
110,Female,International,Guangzhou International Women's Open,"220,000"
111,Female,International,Hansol Korea Open,"220,000"
112,Female,International,Generali Ladies Linz,"220,000"
113,Female,International,HP Japan Women's Open Tennis 2011,"220,000"
114,Female,International,BGL BNP PARIBAS Luxembourg Open,"220,000"

In [23]:
df.to_csv('../Cleaned Data/Major Tennis Tournament Prize Money Data.csv', encoding='utf-8')